checks:
  - schedule: on wednesday at 9:00am
    search:
      q: "repo:filecoin-project/filecoin-plus-large-datasets is:issue is:open label:status:needsDiligence"
      sort: created
    channel: "#fil-plus-notaries"
    message: |
      There are {{items.length}} issues that need diligence:

      {{#each items}}• *<{{this.html_url}}|{{this.title}} (#{{this.number}})>*
      {{/each}}
